/**
 * Service factory — creates service instances from environment variables.
 * These are lightweight wrappers that match the interfaces in context.ts.
 * The actual implementations live in apps/api/src/services/ but since
 * worker is a separate app, we re-import by path alias or duplicate the
 * essential fetch logic here.
 */

import * as crypto from "node:crypto"
import type {
    GitHubServiceInterface,
    VercelServiceInterface,
    NamecheapServiceInterface,
    ResendServiceInterface,
} from "./context.js"

// ─── GitHub Service ──────────────────────────────────────────────

interface GitHubAppAuth {
    appId: string
    privateKey: string
}

class GitHubService implements GitHubServiceInterface {
    private orgName: string
    private auth: GitHubAppAuth
    private installationToken?: string
    private tokenExpiry = 0

    constructor(orgName: string, appId: string, privateKey: string) {
        this.orgName = orgName
        this.auth = { appId, privateKey }
    }

    private generateJWT(): string {
        const now = Math.floor(Date.now() / 1000)
        const header = Buffer.from(JSON.stringify({ alg: "RS256", typ: "JWT" })).toString("base64url")
        const payload = Buffer.from(
            JSON.stringify({ iat: now - 60, exp: now + 600, iss: this.auth.appId })
        ).toString("base64url")
        const data = `${header}.${payload}`
        const sign = crypto.createSign("RSA-SHA256")
        sign.update(data)
        const sig = sign.sign(this.auth.privateKey, "base64url")
        return `${data}.${sig}`
    }

    private async getInstallationToken(): Promise<string> {
        if (this.installationToken && Date.now() < this.tokenExpiry) {
            return this.installationToken
        }
        const jwt = this.generateJWT()
        const installRes = await fetch(
            `https://api.github.com/orgs/${this.orgName}/installation`,
            { headers: { Authorization: `Bearer ${jwt}`, Accept: "application/vnd.github+json" } }
        )
        if (!installRes.ok) throw new Error(`GitHub: failed to get installation (${installRes.status})`)
        const install = (await installRes.json()) as { id: number }
        const tokenRes = await fetch(
            `https://api.github.com/app/installations/${install.id}/access_tokens`,
            { method: "POST", headers: { Authorization: `Bearer ${jwt}`, Accept: "application/vnd.github+json" } }
        )
        if (!tokenRes.ok) throw new Error(`GitHub: failed to get access token (${tokenRes.status})`)
        const tokenData = (await tokenRes.json()) as { token: string; expires_at: string }
        this.installationToken = tokenData.token
        this.tokenExpiry = new Date(tokenData.expires_at).getTime() - 60_000
        return this.installationToken
    }

    private async githubFetch(path: string, options: RequestInit = {}): Promise<Response> {
        const token = await this.getInstallationToken()
        return fetch(`https://api.github.com${path}`, {
            ...options,
            headers: {
                Authorization: `Bearer ${token}`,
                Accept: "application/vnd.github+json",
                "Content-Type": "application/json",
                ...(options.headers ?? {}),
            },
        })
    }

    async createRepo(orgName: string, repoName: string) {
        // Idempotent: check if already exists
        if (await this.repoExists(orgName, repoName)) {
            const res = await this.githubFetch(`/repos/${orgName}/${repoName}`)
            return (await res.json()) as { id: number; name: string; full_name: string }
        }
        const res = await this.githubFetch(`/orgs/${orgName}/repos`, {
            method: "POST",
            body: JSON.stringify({ name: repoName, private: true, auto_init: false }),
        })
        if (!res.ok) throw new Error(`GitHub: failed to create repo (${res.status})`)
        return (await res.json()) as { id: number; name: string; full_name: string }
    }

    async repoExists(orgName: string, repoName: string): Promise<boolean> {
        const res = await this.githubFetch(`/repos/${orgName}/${repoName}`)
        return res.status === 200
    }

    async pushTemplate(repoName: string, templatePath: string): Promise<void> {
        // Create an initial commit with a README placeholder using the Git Data API
        // In production this would clone the full template, but for now we bootstrap with a README
        const content = Buffer.from(
            `# ${repoName}\n\nGenerated by Geenius Platform from template: ${templatePath}\n`
        ).toString("base64")

        // Create a blob
        const blobRes = await this.githubFetch(`/repos/${this.orgName}/${repoName}/git/blobs`, {
            method: "POST",
            body: JSON.stringify({ content, encoding: "base64" }),
        })
        if (!blobRes.ok) throw new Error(`GitHub: failed to create blob (${blobRes.status})`)
        const blob = (await blobRes.json()) as { sha: string }

        // Create a tree
        const treeRes = await this.githubFetch(`/repos/${this.orgName}/${repoName}/git/trees`, {
            method: "POST",
            body: JSON.stringify({
                tree: [{ path: "README.md", mode: "100644", type: "blob", sha: blob.sha }],
            }),
        })
        if (!treeRes.ok) throw new Error(`GitHub: failed to create tree (${treeRes.status})`)
        const tree = (await treeRes.json()) as { sha: string }

        // Create a commit
        const commitRes = await this.githubFetch(`/repos/${this.orgName}/${repoName}/git/commits`, {
            method: "POST",
            body: JSON.stringify({
                message: `chore: initial scaffold from ${templatePath} [geenius]`,
                tree: tree.sha,
            }),
        })
        if (!commitRes.ok) throw new Error(`GitHub: failed to create commit (${commitRes.status})`)
        const commit = (await commitRes.json()) as { sha: string }

        // Create the main branch ref
        const refRes = await this.githubFetch(`/repos/${this.orgName}/${repoName}/git/refs`, {
            method: "POST",
            body: JSON.stringify({ ref: "refs/heads/main", sha: commit.sha }),
        })
        // 422 means ref already exists — update it instead
        if (refRes.status === 422) {
            await this.githubFetch(`/repos/${this.orgName}/${repoName}/git/refs/heads/main`, {
                method: "PATCH",
                body: JSON.stringify({ sha: commit.sha, force: true }),
            })
        } else if (!refRes.ok) {
            throw new Error(`GitHub: failed to create ref (${refRes.status})`)
        }
    }

    async getBranchSHA(repoName: string, branch: string): Promise<string> {
        const res = await this.githubFetch(`/repos/${this.orgName}/${repoName}/git/ref/heads/${branch}`)
        if (!res.ok) throw new Error(`GitHub: failed to get branch SHA (${res.status})`)
        const data = (await res.json()) as { object: { sha: string } }
        return data.object.sha
    }

    async waitForCIPass(repoName: string, commitSHA: string, timeoutMs: number): Promise<void> {
        const deadline = Date.now() + timeoutMs
        while (Date.now() < deadline) {
            const res = await this.githubFetch(
                `/repos/${this.orgName}/${repoName}/commits/${commitSHA}/status`
            )
            if (res.ok) {
                const status = (await res.json()) as { state: string }
                if (status.state === "success") return
                if (status.state === "failure" || status.state === "error") {
                    throw new Error(`CI failed with state: ${status.state}`)
                }
            }
            await new Promise((r) => setTimeout(r, 15_000))
        }
        throw new Error("CI timed out")
    }

    async createDispatchEvent(repoName: string, eventType: string): Promise<void> {
        const res = await this.githubFetch(
            `/repos/${this.orgName}/${repoName}/dispatches`,
            { method: "POST", body: JSON.stringify({ event_type: eventType }) }
        )
        if (!res.ok) throw new Error(`GitHub: failed to create dispatch event (${res.status})`)
    }
}

// ─── Vercel Service ──────────────────────────────────────────────

class VercelService implements VercelServiceInterface {
    private apiToken: string
    private teamId?: string

    constructor(apiToken: string, teamId?: string) {
        this.apiToken = apiToken
        this.teamId = teamId
    }

    private async vercelFetch(path: string, options: RequestInit = {}): Promise<Response> {
        const qs = this.teamId
            ? (path.includes("?") ? `&teamId=${this.teamId}` : `?teamId=${this.teamId}`)
            : ""
        return fetch(`https://api.vercel.com${path}${qs}`, {
            ...options,
            headers: {
                Authorization: `Bearer ${this.apiToken}`,
                "Content-Type": "application/json",
                ...(options.headers ?? {}),
            },
        })
    }

    async createProject(name: string, repoId: string, envVars: unknown[]) {
        const res = await this.vercelFetch("/v9/projects", {
            method: "POST",
            body: JSON.stringify({
                name,
                gitRepository: { type: "github", repo: repoId },
                environmentVariables: envVars,
            }),
        })
        if (!res.ok) throw new Error(`Vercel: failed to create project (${res.status})`)
        return (await res.json()) as { id: string; name: string }
    }

    async getProject(name: string) {
        const res = await this.vercelFetch(`/v9/projects/${name}`)
        if (res.status === 404) return null
        if (!res.ok) throw new Error(`Vercel: failed to get project (${res.status})`)
        return (await res.json()) as { id: string; name: string }
    }

    async addDomain(projectId: string, domain: string) {
        const res = await this.vercelFetch(`/v9/projects/${projectId}/domains`, {
            method: "POST",
            body: JSON.stringify({ name: domain }),
        })
        if (!res.ok && res.status !== 409) throw new Error(`Vercel: failed to add domain (${res.status})`)
    }

    async removeDomain(projectId: string, domain: string) {
        const res = await this.vercelFetch(`/v9/projects/${projectId}/domains/${domain}`, { method: "DELETE" })
        if (!res.ok && res.status !== 404) throw new Error(`Vercel: failed to remove domain (${res.status})`)
    }

    async triggerDeploy(projectId: string) {
        const res = await this.vercelFetch("/v13/deployments", {
            method: "POST",
            body: JSON.stringify({ name: projectId, target: "production" }),
        })
        if (!res.ok) throw new Error(`Vercel: failed to trigger deploy (${res.status})`)
        return (await res.json()) as { id: string; url: string }
    }

    async getDeploymentStatus(deploymentId: string) {
        const res = await this.vercelFetch(`/v13/deployments/${deploymentId}`)
        if (!res.ok) throw new Error(`Vercel: failed to get deployment (${res.status})`)
        return (await res.json()) as { id: string; url: string; readyState: string }
    }

    async setEnvVars(projectId: string, vars: unknown[]) {
        const res = await this.vercelFetch(`/v9/projects/${projectId}/env`, {
            method: "POST",
            body: JSON.stringify(vars),
        })
        if (!res.ok) throw new Error(`Vercel: failed to set env vars (${res.status})`)
    }

    async waitForDomainVerification(projectId: string, domain: string, timeoutMs: number) {
        const deadline = Date.now() + timeoutMs
        while (Date.now() < deadline) {
            const res = await this.vercelFetch(`/v9/projects/${projectId}/domains/${domain}`)
            if (res.ok) {
                const data = (await res.json()) as { verified: boolean }
                if (data.verified) return
            }
            await new Promise((r) => setTimeout(r, 30_000))
        }
        throw new Error(`Domain ${domain} verification timed out`)
    }
}

// ─── Namecheap Service ──────────────────────────────────────────

class NamecheapService implements NamecheapServiceInterface {
    private apiUser: string
    private apiKey: string
    private clientIp: string
    private baseUrl = "https://api.namecheap.com/xml.response"

    constructor(apiUser: string, apiKey: string, clientIp: string) {
        this.apiUser = apiUser
        this.apiKey = apiKey
        this.clientIp = clientIp
    }

    private buildUrl(command: string, params: Record<string, string> = {}): string {
        const qs = new URLSearchParams({
            ApiUser: this.apiUser, ApiKey: this.apiKey,
            UserName: this.apiUser, ClientIp: this.clientIp,
            Command: command, ...params,
        })
        return `${this.baseUrl}?${qs}`
    }

    async checkAvailability(domains: string[]) {
        const url = this.buildUrl("namecheap.domains.check", { DomainList: domains.join(",") })
        const res = await fetch(url)
        if (!res.ok) throw new Error(`Namecheap: failed to check availability (${res.status})`)
        const xml = await res.text()
        return domains.map((domain) => {
            const available = xml.includes(`Domain="${domain}" Available="true"`)
            const priceMatch = xml.match(/RegularRegistrationPrice="([\d.]+)"/)
            const registrarCents = priceMatch ? Math.round(parseFloat(priceMatch[1] ?? "0") * 100) : 1000
            return { domain, available, priceCents: Math.max(1000, Math.ceil(registrarCents * 1.3)) }
        })
    }

    async getPrice(domain: string): Promise<number> {
        const results = await this.checkAvailability([domain])
        return results[0]?.priceCents ?? Math.max(1000, Math.ceil(1000 * 1.3))
    }

    async purchaseDomain(domain: string, years: number) {
        const url = this.buildUrl("namecheap.domains.create", {
            DomainName: domain, Years: String(years),
            RegistrantFirstName: "Geenius", RegistrantLastName: "Platform",
            RegistrantAddress1: "123 Main St", RegistrantCity: "San Francisco",
            RegistrantStateProvince: "CA", RegistrantPostalCode: "94105",
            RegistrantCountry: "US", RegistrantPhone: "+1.4155551234",
            RegistrantEmailAddress: "billing@geenius.dev",
            AuxBillingFirstName: "Geenius", AuxBillingLastName: "Platform",
            AuxBillingAddress1: "123 Main St", AuxBillingCity: "San Francisco",
            AuxBillingStateProvince: "CA", AuxBillingPostalCode: "94105",
            AuxBillingCountry: "US", AuxBillingPhone: "+1.4155551234",
            AuxBillingEmailAddress: "billing@geenius.dev",
            TechFirstName: "Geenius", TechLastName: "Platform",
            TechAddress1: "123 Main St", TechCity: "San Francisco",
            TechStateProvince: "CA", TechPostalCode: "94105",
            TechCountry: "US", TechPhone: "+1.4155551234",
            TechEmailAddress: "billing@geenius.dev",
        })
        const res = await fetch(url, { method: "POST" })
        if (!res.ok) throw new Error(`Namecheap: failed to purchase domain (${res.status})`)
    }

    async setDNStoVercel(domain: string) {
        const parts = domain.split(".")
        const sld = parts[0] ?? ""
        const tld = parts.slice(1).join(".")
        const url = this.buildUrl("namecheap.domains.dns.setCustom", {
            SLD: sld, TLD: tld, Nameservers: "ns1.vercel-dns.com,ns2.vercel-dns.com",
        })
        const res = await fetch(url, { method: "POST" })
        if (!res.ok) throw new Error(`Namecheap: failed to set DNS (${res.status})`)
    }

    async getDomainStatus(domain: string): Promise<string> {
        const parts = domain.split(".")
        const sld = parts[0] ?? ""
        const tld = parts.slice(1).join(".")
        const url = this.buildUrl("namecheap.domains.getInfo", { DomainName: domain, SLD: sld, TLD: tld })
        const res = await fetch(url)
        if (!res.ok) throw new Error(`Namecheap: failed to get domain status (${res.status})`)
        const xml = await res.text()
        const match = xml.match(/Status="([^"]+)"/)
        return match?.[1] ?? "unknown"
    }

    async renewDomain(domain: string) {
        const [sld, ...tldParts] = domain.split(".")
        const tld = tldParts.join(".")
        const url = this.buildUrl("namecheap.domains.renew", {
            DomainName: domain, Years: "1", SLD: sld ?? "", TLD: tld,
        })
        const res = await fetch(url, { method: "POST" })
        if (!res.ok) throw new Error(`Namecheap: failed to renew domain (${res.status})`)
    }
}

// ─── Factory ─────────────────────────────────────────────────────

export function createGitHubService(
    orgName: string | undefined,
    appId: string | undefined,
    privateKey: string | undefined
): GitHubServiceInterface | undefined {
    if (!orgName || !appId || !privateKey) return undefined
    return new GitHubService(orgName, appId, privateKey)
}

export function createVercelService(
    apiToken: string | undefined,
    teamId: string | undefined
): VercelServiceInterface | undefined {
    if (!apiToken) return undefined
    return new VercelService(apiToken, teamId)
}

export function createNamecheapService(
    apiUser: string | undefined,
    apiKey: string | undefined,
    clientIp: string | undefined
): NamecheapServiceInterface | undefined {
    if (!apiUser || !apiKey || !clientIp) return undefined
    return new NamecheapService(apiUser, apiKey, clientIp)
}

// Resend is static — no instance needed, but we provide a factory
// so the caller can use it like the other services.
export function createResendService(): ResendServiceInterface | undefined {
    // Resend doesn't need init-time keys — the API key is per-call
    // (reseller's own key). So we always return the service.
    try {
        // Dynamic import would be needed for the Resend SDK. For now,
        // return undefined — will be implemented when resend is added as
        // a dependency to the worker.
        return undefined
    } catch {
        return undefined
    }
}
