import * as crypto from "node:crypto"

interface GitHubAppAuth {
  appId: string
  privateKey: string
}

interface RepoCreationResult {
  id: number
  name: string
  full_name: string
  html_url: string
  clone_url: string
}

interface CommitStatusResult {
  state: "error" | "failure" | "pending" | "success"
}

interface CheckRunResult {
  status: string
  conclusion: string | null
}

export class GitHubService {
  private orgName: string
  private auth: GitHubAppAuth
  private installationToken?: string
  private tokenExpiry = 0

  constructor(orgName: string, appId: string, privateKey: string) {
    this.orgName = orgName
    this.auth = { appId, privateKey }
  }

  private generateJWT(): string {
    const now = Math.floor(Date.now() / 1000)
    const header = Buffer.from(JSON.stringify({ alg: "RS256", typ: "JWT" })).toString("base64url")
    const payload = Buffer.from(
      JSON.stringify({ iat: now - 60, exp: now + 600, iss: this.auth.appId })
    ).toString("base64url")
    const data = `${header}.${payload}`
    const sign = crypto.createSign("RSA-SHA256")
    sign.update(data)
    const sig = sign.sign(this.auth.privateKey, "base64url")
    return `${data}.${sig}`
  }

  private async getInstallationToken(): Promise<string> {
    if (this.installationToken && Date.now() < this.tokenExpiry) {
      return this.installationToken
    }
    const jwt = this.generateJWT()
    const installRes = await fetch(
      `https://api.github.com/orgs/${this.orgName}/installation`,
      { headers: { Authorization: `Bearer ${jwt}`, Accept: "application/vnd.github+json" } }
    )
    if (!installRes.ok) throw new Error(`GitHub: failed to get installation (${installRes.status})`)
    const install = await installRes.json() as { id: number }

    const tokenRes = await fetch(
      `https://api.github.com/app/installations/${install.id}/access_tokens`,
      { method: "POST", headers: { Authorization: `Bearer ${jwt}`, Accept: "application/vnd.github+json" } }
    )
    if (!tokenRes.ok) throw new Error(`GitHub: failed to get access token (${tokenRes.status})`)
    const tokenData = await tokenRes.json() as { token: string; expires_at: string }
    this.installationToken = tokenData.token
    this.tokenExpiry = new Date(tokenData.expires_at).getTime() - 60_000
    return this.installationToken
  }

  private async githubFetch(path: string, options: RequestInit = {}): Promise<Response> {
    const token = await this.getInstallationToken()
    return fetch(`https://api.github.com${path}`, {
      ...options,
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        ...(options.headers ?? {}),
      },
    })
  }

  async createRepo(orgName: string, repoName: string): Promise<RepoCreationResult> {
    // Idempotent: if repo already exists, return its info
    const existing = await this.getRepoInfo(orgName, repoName)
    if (existing) return existing

    const res = await this.githubFetch(`/orgs/${orgName}/repos`, {
      method: "POST",
      body: JSON.stringify({ name: repoName, private: true, auto_init: false }),
    })
    if (!res.ok) throw new Error(`GitHub: failed to create repo (${res.status})`)
    return res.json() as Promise<RepoCreationResult>
  }

  private async getRepoInfo(orgName: string, repoName: string): Promise<RepoCreationResult | null> {
    const res = await this.githubFetch(`/repos/${orgName}/${repoName}`)
    if (res.status === 404) return null
    if (!res.ok) return null
    return res.json() as Promise<RepoCreationResult>
  }

  async repoExists(orgName: string, repoName: string): Promise<boolean> {
    const res = await this.githubFetch(`/repos/${orgName}/${repoName}`)
    return res.status === 200
  }

  async pushTemplate(repoName: string, templatePath: string): Promise<void> {
    // Use the GitHub Git Data API to push an initial scaffold commit.
    // templatePath determines the plan (e.g. "template-website-vite-react").
    const repo = `${this.orgName}/${repoName}`

    const files = [
      {
        path: "README.md",
        content: `# ${repoName}\n\nGenerated by Geenius Platform.\n\nTemplate: ${templatePath}\n`,
      },
      {
        path: "package.json",
        content: JSON.stringify(
          {
            name: repoName,
            version: "0.1.0",
            private: true,
            type: "module",
            scripts: {
              dev: "vite",
              build: "vite build",
              preview: "vite preview",
            },
            dependencies: { react: "^19.0.0", "react-dom": "^19.0.0" },
            devDependencies: { vite: "^6.0.0", "@vitejs/plugin-react": "^4.0.0" },
          },
          null,
          2
        ) + "\n",
      },
      {
        path: "index.html",
        content:
          '<!DOCTYPE html>\n<html lang="en">\n<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>App</title></head>\n<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>\n</html>\n',
      },
      {
        path: "src/main.tsx",
        content:
          'import React from "react"\nimport ReactDOM from "react-dom/client"\n\nReactDOM.createRoot(document.getElementById("root")!).render(\n  <React.StrictMode>\n    <h1>Welcome</h1>\n  </React.StrictMode>\n)\n',
      },
    ]

    // 1. Create blobs for each file
    const blobShas: { path: string; sha: string }[] = []
    for (const file of files) {
      const blobRes = await this.githubFetch(`/repos/${repo}/git/blobs`, {
        method: "POST",
        body: JSON.stringify({ content: file.content, encoding: "utf-8" }),
      })
      if (!blobRes.ok) throw new Error(`GitHub: failed to create blob for ${file.path} (${blobRes.status})`)
      const blob = (await blobRes.json()) as { sha: string }
      blobShas.push({ path: file.path, sha: blob.sha })
    }

    // 2. Create tree
    const treeRes = await this.githubFetch(`/repos/${repo}/git/trees`, {
      method: "POST",
      body: JSON.stringify({
        tree: blobShas.map((b) => ({
          path: b.path,
          mode: "100644",
          type: "blob",
          sha: b.sha,
        })),
      }),
    })
    if (!treeRes.ok) throw new Error(`GitHub: failed to create tree (${treeRes.status})`)
    const tree = (await treeRes.json()) as { sha: string }

    // 3. Create commit (no parent — initial commit)
    const commitRes = await this.githubFetch(`/repos/${repo}/git/commits`, {
      method: "POST",
      body: JSON.stringify({
        message: "chore: initial scaffold [geenius]",
        tree: tree.sha,
      }),
    })
    if (!commitRes.ok) throw new Error(`GitHub: failed to create commit (${commitRes.status})`)
    const commit = (await commitRes.json()) as { sha: string }

    // 4. Create main branch ref pointing to the commit
    const refRes = await this.githubFetch(`/repos/${repo}/git/refs`, {
      method: "POST",
      body: JSON.stringify({ ref: "refs/heads/main", sha: commit.sha }),
    })
    // 422 means ref already exists — try update instead
    if (refRes.status === 422) {
      const updateRes = await this.githubFetch(`/repos/${repo}/git/refs/heads/main`, {
        method: "PATCH",
        body: JSON.stringify({ sha: commit.sha, force: true }),
      })
      if (!updateRes.ok) throw new Error(`GitHub: failed to update ref (${updateRes.status})`)
    } else if (!refRes.ok) {
      throw new Error(`GitHub: failed to create ref (${refRes.status})`)
    }
  }

  async getBranchSHA(repoName: string, branch: string): Promise<string> {
    const res = await this.githubFetch(
      `/repos/${this.orgName}/${repoName}/git/ref/heads/${branch}`
    )
    if (!res.ok) throw new Error(`GitHub: failed to get branch SHA (${res.status})`)
    const data = await res.json() as { object: { sha: string } }
    return data.object.sha
  }

  async waitForCIPass(repoName: string, commitSHA: string, timeoutMs: number): Promise<void> {
    const deadline = Date.now() + timeoutMs
    while (Date.now() < deadline) {
      const res = await this.githubFetch(
        `/repos/${this.orgName}/${repoName}/commits/${commitSHA}/status`
      )
      if (res.ok) {
        const status = await res.json() as CommitStatusResult
        if (status.state === "success") return
        if (status.state === "failure" || status.state === "error") {
          throw new Error(`CI failed with state: ${status.state}`)
        }
      }
      await new Promise((r) => setTimeout(r, 10_000))
    }
    throw new Error("CI timed out")
  }

  async createDispatchEvent(repoName: string, eventType: string): Promise<void> {
    const res = await this.githubFetch(
      `/repos/${this.orgName}/${repoName}/dispatches`,
      { method: "POST", body: JSON.stringify({ event_type: eventType }) }
    )
    if (!res.ok) throw new Error(`GitHub: failed to create dispatch event (${res.status})`)
  }
}
